STAGE : "prod"
REGION : "ap-southeast-1"
LOG_RETENTION: 3
AZURE_FACE_API_SUBSCRIPTION_KEY: "4fcf527a5a0f400b9417f159dccd5988"
CASTING_ASIA_AUTHORIZATION : "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicG9zdGdyZXMiLCJleHAiOjE4MjgzMjc4NzV9.gNly-rwdo6BkA355PCJoLnj4MWwjtTEz4HCV7CSeppU"
CASTING_ASIA_API : "https://api.casting-asia.com"